[meta]
title = "PyDino"
author = "Gabriel Mitelman Tkacz"
license = "MIT License"

[screen]
bg_color = [255, 255, 255]
fps = 15
dimensions = {width = 1280, height = 720}

[game]
gravity = 0.5
speed = 10
high_score = 0